### ISSUE TITLE
[Fusayasaさん質問]Wookong bioの公式アプリは利用することが可能でしょうか

### ISSUE THREAD

**Issue by cooltiger** [extropiescom/bladeX#1]
-  日本語
GithubのBladeXリポジトリにあるテストアプリではなく、Wookong bioの公式アプリは利用することが可能でしょうか？
そちらを開発時の参考に触ってみたいと考えています

-  中国語
是否有Wookong bio的官方应用程序可以使用， 而不是Github的BladeX库中的测试应用程序。
想在开发时参考一下

**Comment by chesterliliang** [comment]
We have our Gemma APP working with WOOKONG Bio which support EOS. It is not formal released. We will try to give out a beta version  once ready.

**Comment by cooltiger** [comment]
@chesterliliang   Can you give an about time to got the beta version ? one week or one month, etc ?

**Comment by chesterliliang** [comment]
I will check with Steven who in charge of the dev of Gemma. I think ot will take 1 or 2 weeks.

**Comment by tatsuya0505** [comment]
先日いただいたWookongの公式アプリと
以下のDEMO版は同じものですか？
https://github.com/extropiescom/BladeX_iOS

**Comment by cooltiger** [comment]
> 先日いただいたWookongの公式アプリと
> 以下のDEMO版は同じものですか？
> https://github.com/extropiescom/BladeX_iOS

之前给日方的wookong 官方程序(TestCompileDemo.ipa) 和
https://github.com/extropiescom/BladeX_iOS 
demo版本是同一个版本吗？

**Comment by eshangui** [comment]
yes, they are the same version

**Comment by cooltiger** [comment]
問題解決のため、クローズします。
