### ISSUE TITLE
登録するカード名の文字数制限について

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#10]
登録するカード名の文字数制限はありますか？

**Comment by akari61** [comment]
@chesterliliang 
Thank you for your reply.
Please tell us about the character limit for the card name.
Also please let me know the type of characters that can be used.

**Comment by cooltiger** [comment]
中文翻译：
- 1. 登陆卡名字时候的字数限制
- 2. 以及可以使用什么字符？

**Comment by chesterliliang** [comment]
卡片登录名字是指蓝牙广播名称吗

**Comment by cooltiger** [comment]
@akari61 
翻訳：カード名登録は何を示してますか？Bluetoothの broadcast時の名前の事ですか？

呉のコメント：
具体的に、どこの手順で発生した登録を教えて頂ければ特定しやいです。
または、API利用時の事ならば、Function名を提示してください。

**Comment by cooltiger** [comment]
> Memo
> 
> * カードごとのユニークIDはある(工場生産時に付与される)
> * 5-16桁の数字

16桁以下の数字です。

> * 独自に名前を設定することはできない。
