### ISSUE TITLE
暗証番号の桁数設定について

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#11]
暗証番号の桁数はこちらで決めれますか？

**Comment by akari61** [comment]
@chesterliliang 
Thank you for your reply :)
So it means that we can choose the length in 6-16?

**Comment by cooltiger** [comment]
中文翻译：
    密码设定多少位，可以自己决定吗？
    6-16位中间，可任意选择吗？

**Comment by ximinchao** [comment]
Length of password could be any number between 6 and 16
