### ISSUE TITLE
指紋と暗証番号を両方忘れた場合に対処方法はあるか

### ISSUE THREAD

**Issue by akari61** [extropiescom/bladeX#12]
指紋と暗証番号を両方忘れた場合にはどのような対処法がありますか？
If a user forgets both ingerprint and PIN, how do they solve it?

**Comment by cooltiger** [comment]
中文翻译：
  如果指纹和PIN密码都忘记了，怎么办？

**Comment by ximinchao** [comment]
In this case, user should do the following steps to restore his wallet:
1. Find out his mnemonics which was recorded when he created the wallet.
2. Format the device.
3. Create a new wallet on device using "Import mnemonics" way, and input mnemonics found in the 1st step.

**Comment by ximinchao** [comment]
@fussa2323 
Device dosen't need PIN to format, user can format it freely.

**Comment by cooltiger** [comment]
- 個人的な意見：フォーマットはOSの再インストールような事です。 ハードウェア上の認証がないですが、ソフト側のコントロールができます。（導入するニーモニックの事前検証など）。
- 誤フォーマットを防ぐために、警告を出したり、入力したニーモニックによってカードオーナーの確認したら、どうですか？
- なぜフォーマットはPIN不要：個人考え方：PCフォーマット時、フォーマットソフトがあれば、認証なしフォーマットできたと思います。

**Comment by cooltiger** [comment]
中国側の回答：

- 1、指紋やPINが失われている場合は、物理的にBIOの使用することはできません。フォーマットしかできません。この時PINなしで、ユーザーのフォーマットを許可する必要があります。工場出荷時の状態にするためです。

- 2、ニーモニックがあるので、デジタル資産が失ってません。フォーマット後、ニーモニックをインポートすることによって、資産を回復することができます。

**Comment by fussa2323** [comment]
1、指紋やPINが失われている場合は、物理的にBIOの使用することはできません。フォーマットしかできません。この時PINなしで、ユーザーのフォーマットを許可する必要があります。工場出荷時の状態にするためです。
2、ニーモニックがあるので、デジタル資産が失ってません。フォーマット後、ニーモニックをインポートすることによって、資産を回復することができます。

**Comment by cooltiger** [comment]
@akari61 問題がなかったら、クローズを御願いします。
