### ISSUE TITLE
デバイスの登録を削除した場合の動作について

### ISSUE THREAD

**Issue by akari61** [extropiescom/bladeX#13]
アプリからデバイスを削除した場合
1. 再度同じデバイスをアプリに登録するには何が必要になりますか？
2.その場合、ニモニックの再表示は可能ですか？

If we delete hardware wallet from Ginco application
1. What do we need to register the same wallet again to Ginco app?
2.In the above case, is it possible to redisplay the mnemonic?

**Comment by cooltiger** [comment]
**中文翻译：**
   如果从app中把硬件钱包删除后，
   1.  想再次将其登陆到app的话，需要怎么做？
   2.  这种情况下，是否能再次显示助记词？

**Comment by chesterliliang** [comment]
这个涉及问题用户(Ginco)如何设计删除行为的效果。如果删除仅仅是清除软件缓存的话，Bio内部可以不进行任何操作，再次连接后，完成卡片主人身份认证后，则原数据依然可用。如果在删除时同时格式化了卡片，再次连接时，则视同新卡。目前，基于安全性考虑，硬件钱包暂不提供二次助记词显示。

**Comment by cooltiger** [comment]
> 完成卡片主人身份认证

具体用什么去完成？Ginco想知道的应该是用什么手段如何去恢复吧。

**Comment by fussa2323** [comment]
Memo

- ペアリングが終わったら認証が必要、Pinコード or 指紋
- Wookong Bioは未接続時でも表示できる
- 再接続ができる、スマートフォンの中に、wookong bioのMACアドレスをデバイスの中にキャッシュしてある
- 仮にMACアドレスがキャッシュされていない場合は、情報の再読込をすればいい(その際に認証が必要)
- ニモニックの再表示はできない

**Comment by fussa2323** [comment]
- 再表示、再接続に関わらず、ペアリング時に必ず認証フローを挟むことが仕様としてはおすすめ

**Comment by cooltiger** [comment]
@akari61 問題がなかったら、クローズを御願いします。
