### ISSUE TITLE
ファームウェアアップデートについて

### ISSUE THREAD

**Issue by akari61** [extropiescom/bladeX#14]
ファームウェアアップデートについて

1.  PCと接続してファームウェアアップデートを行う一連のフローを教えてください。
2. アップデートの見本を頂きたいです。
3. こちらでドメインを準備し、ユーザーはそのURLにアクセスしてアップデートを行う形になりますか？

About firmware update

1. Please tell me the flow of a series of steps for update the firmware.
2. I would like to receive a sample of the update.
3. Do we need prepare the domain and will the user access the URL to update it?

**Comment by chesterliliang** [comment]
更新的流程是 下载，校验下载，写入卡片，内部校验，内部解密，启用。 对用户来讲，是一键完成的。目前这个工具是工程版本的，后续用户版本，我们希望是wookong团队来制作，当然，会有Ginco的logo在。Ginco也可以提出软件建议。

**Comment by fussa2323** [comment]
Memo

- 直接Appをつかってアップデートはできない
- 公式サイトから、更新用のソフトウェアをダウンロードして、PCで更新する必要がある
- ファームウェアアップデートのページを組み込んでつくってくれる
- ファームウェアアップデート用のページはWookong側で作る
- ファームウェアアップデートの更新通知があったほういい
- ファームウェアアップデート更新の方法→サーバ側でバージョンを取るAPIがあるので、それと照らしあわせて、確認し、最新でなければ通知を出す

**Comment by cooltiger** [comment]
@akari61 問題がなかったら、クローズを御願いします。
