### ISSUE TITLE
カードのデザインデータについて

### ISSUE THREAD

**Issue by akari61** [extropiescom/bladeX#15]
電源がONになる際とBluetoothがONになる際に、青と緑のランプが光ると思います。
1.こちらの位置を変更するのは難しいですか？
2.固定位置の場合、デザインデータにランプの位置のガイドを引いていただけますか？

Blue and green lamps will light when the power and Bluetooth turns on.
1. Can you change this position?
2. If it has to be fixed position, can you draw a guide on the lamp position in the design data(.ai)?

**Comment by cooltiger** [comment]
**中文翻译：**
  我们知道：蓝和绿灯在电源ON和蓝牙ON的时候，会亮。那么：
  1，  灯的位置可以改变吗？
  2，  如果位置是固定的话，能不能在卡片的设计文件上标出灯的位置（*.ai）?

**Comment by chesterliliang** [comment]
灯的位置目前无法改变，卡片AI对灯的描述可能存在制作工差，我们不建议卡面设计时，特殊标出灯的位置，因为可能有误差。当然，如果是说明书制作的话，示意图可以提供，这个没有问题。

**Comment by cooltiger** [comment]
@akari61 問題がなかったら、クローズを御願いします。
