### ISSUE TITLE
記載するID等について

### ISSUE THREAD

**Issue by akari61** [extropiescom/bladeX#16]
1.モデルナンバーはHW-WKFP-01と記載して良いですか？
1. Can I describe the model number as "HW - WKFP - 01" in our product?

2.FCC-IDについてはこちらで番号を取得する必要がありますか？
Do we need to get our own FCC-ID?
<img width="538" alt="2018-11-25 9 26 11" src="https://user-images.githubusercontent.com/1402765/48974185-33d19780-f094-11e8-9518-38b0c0c176c4.png">

3.下記のマークについて、内容を教えてください。また番号の取得の必要がありますか？
Please tell me about the marks below. Do you also need to get a own number?
![2018-11-24 16 43 29](https://user-images.githubusercontent.com/1402765/48974186-37fdb500-f094-11e8-84a2-390b16939801.png)

**Comment by cooltiger** [comment]
**中文翻译**

1.  我们 能不能在卡上写上我们的产品编号：HW - WKFP - 01 ？
2. FCC-ID , 我们自己需要重新取得吗？（还是使用中方取得的FCC-ID ?）
3. 下图的mark是什么意义？ 我们自己需要重新取得吗？（还是使用中方取得的 ?）

**Comment by chesterliliang** [comment]
我们不建议做这些更改，因为FCC测试需要提供卡的全部设计文件，这点目前似乎有所不便。

**Comment by cooltiger** [comment]
@chesterliliang 

> 我们不建议做这些更改，因为FCC测试需要提供卡的全部设计文件，这点目前似乎有所不便。

1， 现在的model标的是WOOKONG Bio。 Ginco的意思应该是model 标上自己的产品编号。

2.  关于认证号，之前沟通的是，中国这边已经在做了。 所以Ginco就不需要另外申请了，
     而是在印刷时使用中国这边取得的号就好了。是吗？

以上内容例会上一起确认。
如果我理解有误，那非常抱歉。

**Comment by fussa2323** [comment]
Memo

- マークについては、中国側で認証申請中
- モデルネームについてはWookong Bioとして申請しているので変更はできない
- 認証した証として表示する必要がある

**Comment by cooltiger** [comment]
追加：

認証と関係ない項目（APP model, Product versionなど）を用いて、
KincoカードのモデルNoを入れたら良いかと思います。

ご検討ください。

**Comment by cooltiger** [comment]
@akari61 問題がなかったら、クローズを御願いします。
