### ISSUE TITLE
Technical Questions

### ISSUE THREAD

**Issue by fussa2323** [extropiescom/bladeX#17]
## デバイスのセキュリティについて
関連会社やお客さんにハードウェアウォレットの仕様の説明をする機会があります。
その際に必要な情報がありますので以下の項目が分かるような資料をいただけますでしょうか。

1. チップの規格sc300はarmの規格名だと思うのですが、製造場所や製造メーカーはどこでしょうか.
2. バッテリーの稼働時間や、バッテリーの規格について教えてください。
3. ディスプレイの解像度を教えてください。
4. ディスプレイに表示できる文字数は何文字でしょうか。

## About the device security
We have the opportunity of explaining the specification of the Kinco.
Then, we need to talk about wookong bio in detail.
Could you tell us more about the specification or send the document as follows : 

1. Where is the securecore made in? Who is the manufacturer of the securecore (I understand the sc300 is just a standard name).
2. What is the Battery's standard? How long does the battery work?
3. How much resolution does the display has?
4. How much number of characters can display show?

**Comment by fussa2323** [comment]
李良's Answer


Here is a brief anwser of the  specification questions:
1. The secure element is made by UMC.com in Singapore.
2. The battery is 22mAh and can support Bio to run in full power mode over 40 minutes. To enable low power mode step by step through firmware update could enhance the perfermance serval times.
3. The resolution of screen is 128x80 in total and we use 120x64 as the test aera.
4. The font we chose is 8x16. So 15 charaters one line and 4 lines one page. 

The waiting mode means only BLE connection, not any other operation. So the current is  about 1/4 of the full power mode. 

By step by step, I mean we need some time to make the firmware switch between full power mode and waiting(low power) mode works right and test it well. We will download the best version before MP shipping and keep optimise it while upgrading.

**Comment by fussa2323** [comment]
### Additional Question

1. What's the name of the factory or company that prints wookong bio?
2. How secure logistics do you plan to ship from china to Japan?

**Comment by cooltiger** [comment]
@fussa2323 問題がなかったら、クローズを御願いします。
