### ISSUE TITLE
The number of mnemonic phrase

### ISSUE THREAD

**Issue by fussa2323** [extropiescom/bladeX#18]
- The test version of wookong bio has 12 mnemonic phrase.
- Kinco is also 12 mnemonic phrases?

**Comment by ximinchao** [comment]
1. Bio importMne interface support 12/15/18/21/24 mnemonic phrases.
2. Bio generateSeed_GetMnes need a int arg of seedLen, which could be [16,32] and must be multiple of 4.

see also: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
|  ENT    | CS   | ENT+CS |  MS  |
+-------+----+--------+------+
|   128   |   4   |   132    |    12   |
|    160  |   5   |   165    |    15   |
|    192  |   6   |   198    |    18   |
|    224  |   7   |    231   |    21   |
|    256  |   8   |    264   |    24   |
