### ISSUE TITLE
[Tatsuyaさん質問]　BladeX APIのSet Image Dataが何をセットするかもうかがいたいです。

### ISSUE THREAD

**Issue by cooltiger** [extropiescom/bladeX#2]
- 日本語
　BladeX APIのSet Image Dataが何をセットするかもうかがいたいです。

- 中国語
 BladeX API的Set Image Data中设置什么内容。

**Comment by chesterliliang** [comment]
It is an API to set the screen logo when power off. It is supposed not the API for user API but to initialise the card before released.

**Comment by tatsuya0505** [comment]
I see. Thank you.

**Comment by cooltiger** [comment]
大丈夫そうですので、クローズします。
