### ISSUE TITLE
iOSのFrameworkおよびデバイスの仕様について

### ISSUE THREAD

**Issue by matsuokah** [extropiescom/bladeX#22]
4点質問したいです。

# `PAEW_GenerateSeed`について
① すでにGenerateSeedしてあるかどうかを判定するAPIや情報はありますか？

# バッテリーについて
① 残量の上限と下限の数値が知りたいです
② 残量の上限値はデバイスによって違いますか？(今後、デバイスの型によって変わる可能性がありますか？)
③ バッテリーの残量は時間にすると１あたり何分になるか？(残量の値が120の場合、何分みたいな目安が知りたいです)

**Comment by cooltiger** [comment]
中文翻译：

以下的四个提问

> # `PAEW_GenerateSeed`について
> ① すでにGenerateSeedしてあるかどうかを判定するAPIや情報はありますか？

关于 `PAEW_GenerateSeed`
①　有没有如下功能的API或者取得的方法：
判断是否已经GenerateSeed。

> # バッテリーについて
> ① 残量の上限と下限の数値が知りたいです
> ② 残量の上限値はデバイスによって違いますか？(今後、デバイスの型によって変わる可能性がありますか？)
> ③ バッテリーの残量は時間にすると１あたり何分になるか？(残量の値が120の場合、何分みたいな目安が知りたいです)

关于电池：
①　电量的余量的上限值和下限值是多少？
②　电量的余量的上限值会随着今后产品型号的改变而改变吗？
③　电量的余量，换算成时间的话，1个单位相当于几分钟？（比如余量值为120的话，大概是几分钟？）

**Comment by eshangui** [comment]
About `PAEW_GenerateSeed`:

The `ucLifeCycle` field in `PAEW_DevInfo` struct shows the life cycle of the hardware, and `ucLifeCycle == PAEW_DEV_INFO_LIFECYCLE_USER`  means the seed is already generated or imported.

you may use the following to get device life cycle:

C :
```c
PAEW_DevInfo devInfo = {0};
nDevInfoType |= PAEW_DEV_INFOTYPE_LIFECYCLE;
iRtn = PAEW_GetDevInfo(pPAEWContext, nDevIndex, nDevInfoType, &devInfo);
if (devInfo.ucLifeCycle == PAEW_DEV_INFO_LIFECYCLE_USER) {
    //seed does exist
} else {
    //seed does not exist
}
```

Swift:
```swift
devInfoType |= PAEW_DEV_INFOTYPE_LIFECYCLE
var devInfo = PAEW_DevInfo.init()
iRtn = PAEW_GetDevInfo(pPAEWContext, devIdx, devInfoType, &devInfo)
if devInfo.ucLifeCycle == PAEW_DEV_INFO_LIFECYCLE_USER {
    //seed does exist
} else {
    //seed does not exist
}
```

**Comment by chesterliliang** [comment]
上限为142，偶尔在充电结束时会出现大于142的数值，将其视为满电即可。下限为124，视为0%. 升级电池或硬件时，电量值表示可能会更新。最新固件中，量程18，对应70工作分钟，大致为线性分布。所以数值1基本可视为4分钟。

**Comment by cooltiger** [comment]
> # バッテリーについて
> ① 残量の上限と下限の数値が知りたいです

上限値：142。それ以上のになった場合、充電量１００％とみなします。
下限値：124。残量０％とみなします。

> ② 残量の上限値はデバイスによって違いますか？(今後、デバイスの型によって変わる可能性がありますか？)

電池または、ハードウェアをアップグレードしたら、
数値の変更があるかもしれません。

因みに、ファームウェア更新時、数値の変更可能性がほぼありません（ファームウェア仕様上）。

> ③ バッテリーの残量は時間にすると１あたり何分になるか？(残量の値が120の場合、何分みたいな目安が知りたいです)

今、上限値と下限値の差18となり、対応作業可能時間が70分です（Linear distribution）ので、
数値１あたり、4分ぐらいと見れば良いです。

**Comment by matsuokah** [comment]
Thank you.
