### ISSUE TITLE
[Tatsuyaさん質問]TestCompileDemoアプリのSwift版はありますか？

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#4]
TestCompileDemoアプリのSwift版はありますか？

**Comment by cooltiger** [comment]
中文翻译：
TestCompileDemo 程序的Swift版本有吗？ 有的话，请给一下LINK。

**Comment by eshangui** [comment]
Sorry for the inconvenience, but currently we do not have a swift version.

**Comment by tatsuya0505** [comment]
Ok. Thank you.
