### ISSUE TITLE
[Tatsuyaさん質問]bladeX iOS APIのGet finger print listについて

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#5]
PAEW_GetFPListは複数の指紋認証登録情報を返すのか？
指紋認証は複数登録することができるのか？

**Comment by chesterliliang** [comment]
Yes. Retrurn list will be the index of the fingerprints template. If there are three, the list will be 000102.

**Comment by tatsuya0505** [comment]
I see. Thank you.
