### ISSUE TITLE
[Tatsuyaさん質問]bladeX iOS APIのRestore trade address from derive pathについて

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#7]
PAEW_DeriveTradeAddressの引数puiDerivePathには例えばETHの場合だと何を渡せばいいですか？

**Comment by eshangui** [comment]
Hello, you can refer to [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) and [SLIP44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

 According to the documents, all coins  should have a independent derive path in this format: 
```
m / purpose' / coin_type' / account' / change / address_index
```

So, the derive path of ETH should be like this: 
```
m/44'/60'/0'/0/0
```
The first **m** means 0, **44'** means 0x8000002C, the **'**  means the highest bit is 1 and Dec44 == Hex2C, **m** and **44'** are all constants defined in BIP44, and **60'** which mean 0x8000003C is the coin type of ETH defined in SLIP44, **0'** which means 0x80000000 stands for account, according to BIP44, its index should start from 0, the last 0/0 stands for change and start_index, the two values should also start from 0.

**Comment by cooltiger** [comment]
中文翻译：
关于PAEW_DeriveTradeAddress的puiDerivePath参数，例如在ETH的情况下，应该传递什么内容？

**Comment by tatsuya0505** [comment]
I see.
Thank you.
