### ISSUE TITLE
[Tatsuyaさん質問]アドレスの表記について

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#8]
ハードウェア側にアドレスの表示は可能ですか？

**Comment by cooltiger** [comment]
> ハードウェア側にアドレスの表示は可能ですか？

中文翻译：
硬件卡上能显示 账号地址吗？

**Comment by chesterliliang** [comment]
Yes.  We suggest when the APP tries to show or copy the address, it should be confirmed on the E-ink screen. The para nShowOnScreen of getTradeaddress function will enable the display.

**Comment by eshangui** [comment]
Please refer to function [**PAEW_GetTradeAddress**](https://github.com/extropiescom/bladeX/wiki/bladeX-iOS-API-list#215-get-coin-address-called-after-paew_derivetradeaddress), NOTE that this must be called after **PAEW_DeriveTradeAddress** returns **PAEW_RET_SUCCESS**

**Comment by tatsuya0505** [comment]
I see. Thank you.
