### ISSUE TITLE
[Tatsuyaさん質問]ハードウェア側のBluetoothのライトの位置を変更するとはできないか

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#9]
ハードウェア側のBluetoothのライトの位置を変更するとはできないか？

**Comment by cooltiger** [comment]
> ハードウェア側のBluetoothのライトの位置を変更するとはできないか？

中文翻译：
硬件卡的蓝牙的亮灯位置是否可以更改？

**Comment by chesterliliang** [comment]
I am afraid we can not modify the position of the LED in this generation product. The layout was frozen weeks ago and the toolings for mass production are under-going.

**Comment by tatsuya0505** [comment]
Ok. Thank you.
